### ISSUE TITLE
激光炮塔的追踪算法有问题吧

### ISSUE THREAD

**Issue by Ventulus-lab** [v-limc/oni-mods#5]
年龄相同，应该选择Reproduction繁殖度最小的，而不是Incubation孵化度最小吧，后者是用在蛋上的。。
不知为何出现了一会打这个一会打那个的乱打情况，，

**Comment by Ventulus-lab** [comment]
我找到你的bug在哪了。你的代码中在选取目标时有个设置“被困”标记。而玩家用这个都是畜舍中有“小动物放生点”，会“将困住的小动物放回世界中”，不仅作用于捆绑也作用于被困。结果复制人跑得够快就会把打了一半血的小动物麻袋装上跑小动物放生点放一次，而这个时候炮台就打不到小动物就会切换目标。最后结果就是留下一大堆残血小动物。。而小动物又不会自动回血

**Comment by v-limc** [comment]
已解决
